### PR TITLE
Behaviour for heavy pages and hidden elements; code cleanup

### PR DESCRIPTION
**Pull request by JelleDekker**
Updated behaviour:
- Parts of the page that are not shown (e.g. tab
container; closed
groupbox) are not loaded until opened by the user.
This makes the widget
also usable when the MF isn't slow, but the page
takes time to process.
- It's now possible to run the widget without a
MF. Again for heavy
pages
- The return object of the MF is now used.
This means you can open pages
wich are based on a different entity than
the context object.
- Changed CSS to no longer use absolute positioning,
for use in
groupboxes

Cleanup:
- Added "node_modules" to .gitignore and
added package and gulpfile, sow
people can now run their own build
software
- Removed unused Dojo imports
- Changed parts of the code to be
closer to default Mx widget style

### CODE REVIEW

**Comment by JelleDekker** [comment]
Update regarding previous pull request, found out that there was an error in processing the MF callback, that's fixed now.

**Comment by joelvdgraaf** [comment]
Thanks for your work! I really appreciate it! To have better code and new functions I wasn't aware off. 
On a constructional level I don't agree on everything. To replace the properties in a general category 'settings' isn't conform the widget conventions, referring to https://docs.mendix.com/refguide7/common-widget-properties

Because of the complete code replacing I have some questions:
- Your using a variable '_contentShown', but it set true before the microflow is started. The content is shown when the function '_showPage' is executed? How do you see that?
- Can you please update the test project with the new functionalities including the complete page loading referring to your text 'Again for heavy pages'.
- Do you use 'this.domNode.offsetParent' for checking if the widget is inside a closed groupbox or tabpage?

**Comment by JelleDekker** [comment]
I set _contentShown early because otherwise you risk the content being loaded multiple times when update is called more often (Mendix does this sometimes). Perhaps _loadingStarted or something would be a better name.

I have everything under settings because the amount of options is very small, this makes it easier to configure the widget in the modeler. Behaviour is normally also used for OnChange and OnClick microflows, not for DataSource/Loading MF's.

I use 'this.domNode.offsetParent' to check if the item is rendered on the page or not. If it's in a closed groupbox or tab container this value will be null. See also http://stackoverflow.com/questions/19669786/check-if-element-is-visible-in-dom

**Comment by joelvdgraaf** [comment]
Hi Jelle. I've tested your solution, but what you say: "It's now possible to run the widget without a
MF. Again for heavy pages" isn't working. 
When I put the widget in a page without a microflow, the widget is showing a loader, but the Mendix loader will come up too. Can you please test this and come with a testproject? 
Thank you in advance

**Comment by JelleDekker** [comment]
Hi Joel,

Unfortunately the Mendix loader will always pop-up when it's loading a page and it thinks it takes too long. I haven't found a way to avoid that by loading the page in the background, Mendix simply doesn't have an API for that (it should!).

I've actually tried to load the hidden content in the background (after the visible content was loaded), but as you said, Mendix unfortunately has no way to hide the progress bar when loading a page. The only possible way would be to search the page for it and then hide it, but I thought that to be a too ugly solution.

So what I use the (adapted) version of the widget for is a very heavy page with many groupboxes (could also have been tabs but the our visual design required groupboxes). Then I changed the widget to only trigger the loader when the content is actually displayed (groupbox is opened). In this way the page isn't heavy anymore, each groupbox loads quickly and the page itself also, because the content is broken into pieces which are only loaded when needed. 

I should have made the description clearer. With the adaptations you can cut a large page into many small pieces, and it will load much faster even if it's the page that's heavy and not the MF. But only if you make sure (by initially hiding content in closed containers) that the pieces are not loaded all at once.

**Pull request merged**
